### ISSUE TITLE
能否将《Go轻松学》出版为gitbook的版本?

### ISSUE THREAD

**Issue by LeonZhu1981** [jemygraw/TechDoc#4]
Hi, jemygraw,

我有幸阅读了Go轻松学的iOS版本, 发现这是一本非常适合入门的golang学习教程. 但是由于只提供了android和iOS版本, 不便于在PC上进行学习.(例如: copy code, run, view run result etc). 因此我计划将《Go轻松学》利用gitbook制作电子版本, 不知道能否使用这个repository的markdown文档. gitbook当中将会保留你的版权信息. 并在制作好之后, release之前交由你review. 不知是否可行?

**Comment by LeonZhu1981** [comment]
http://golanghome.com/post/14 发完上一个issue才发现的. 不过只有go轻松学的基础部分. 没有示例部分了?

**Comment by jemygraw** [comment]
AS YOU LIKE. JUST DO IT.
