### ISSUE TITLE
goroutine有错

### ISSUE THREAD

**Issue by yb3616** [jemygraw/TechDoc#6]
1000以内能被3或5整除的正整数和这个例子有误，我使用你代码，并去掉goroutine后输出233168，而你的原程序输出100498。且你也打印运行时间了，难道没发现运行时间没多大改变吗？因为你的代码只使用一个核，需要修改GOMAXPROCS参数，改后发现偶尔会输出不同的数。还是多channel省心。若以上有理解错误的，望能指出

**Comment by jemygraw** [comment]
是的，原来的例子有错误，请参考新版本：https://github.com/jemygraw/TechDoc/blob/master/Go%E8%BD%BB%E6%9D%BE%E5%AD%A6/go_tutorial_9_parallel_compute.md
